### ISSUE TITLE
Add Dropdown menu with Workspace

### ISSUE THREAD

**Issue by bricemaurin** [kamesstory/AsanaTab#2]
Hey Jason 👋 
Thanks for this great extension. I use it for a few days and it's really a greeeeat addition to asana. Way closer to the values the term "asana" returns to. Thanks a lot !

I have a few requests, maybe you can add it if that's not too much work ? if not, i'd understand, let me know.

1st one is about the "add task" modal:
![image](https://user-images.githubusercontent.com/4593634/109933616-eb21d380-7ccb-11eb-9805-b7292ed2bb0c.png)

When being in multiple workspace, you have to manually type the workspace name. It'd be great to be able to select it from a list (as you already have the workspace names)

**Comment by jasonhfwang** [comment]
Hey — absolutely agree with this, I've changed the Workspace field to a dropdown. The change should be out within the next week or two once Google approves the latest version in the Chrome web store.

**Comment by bricemaurin** [comment]
Great news 🤩 🤩
Thanks !
